export interface AircraftEntry {
  id: string
  manufacturer: string
  model: string
  year: number | null
  category: 'SE' | 'ME' | 'Turboprop' | 'Jet' | 'Helicopter' | 'LSA' | 'Experimental'
  engineType: 'Piston' | 'Turbine' | 'Electric' | 'Rotary'
  engineCount: number
  horsepower: number | null
  fuelType: '100LL' | 'JetA' | 'MOGAS' | 'Electric'
  seatsTotal: number
  cruiseSpeedKts: number | null
  rangeNm: number | null
  ceilingFt: number | null
  usefulLoadLbs: number | null
  fuelCapacityGal: number | null
  burnRateGph: number | null
  certifications: ('VFR' | 'IFR' | 'Aerobatic' | 'Commercial' | 'Training' | 'Cargo' | 'Night')[]
  commonUse: string
  imageUrl: string
  imageCredit: string
  wikipediaUrl: string | null
}

export const aircraftDatabase: AircraftEntry[] = [
  // ── SINGLE ENGINE PISTON ───────────────────────────────────────────────────
  {
    id: 'cessna-172-skyhawk',
    manufacturer: 'Cessna',
    model: '172 Skyhawk',
    year: 1956,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 180,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 122,
    rangeNm: 640,
    ceilingFt: 14000,
    usefulLoadLbs: 878,
    fuelCapacityGal: 53,
    burnRateGph: 8.5,
    certifications: ['VFR', 'IFR', 'Training', 'Night'],
    commonUse: 'The most popular training aircraft in the world. Forgiving, stable, and widely available at flight schools.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Cessna_172S_Skyhawk_SP%2C_Private_JP6817606.jpg/1280px-Cessna_172S_Skyhawk_SP%2C_Private_JP6817606.jpg',
    imageCredit: 'Wikipedia / Kgbo',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_172',
  },
  {
    id: 'cessna-182-skylane',
    manufacturer: 'Cessna',
    model: '182 Skylane',
    year: 1956,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 230,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 145,
    rangeNm: 915,
    ceilingFt: 18100,
    usefulLoadLbs: 1000,
    fuelCapacityGal: 88,
    burnRateGph: 12,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'Workhorse cross-country touring aircraft. More power and payload than the 172, popular for family travel and instrument training.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Cessna_182T_Skylane.jpg/1280px-Cessna_182T_Skylane.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_182',
  },
  {
    id: 'cessna-152',
    manufacturer: 'Cessna',
    model: '152',
    year: 1977,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 110,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 107,
    rangeNm: 415,
    ceilingFt: 14700,
    usefulLoadLbs: 589,
    fuelCapacityGal: 26,
    burnRateGph: 6,
    certifications: ['VFR', 'Training'],
    commonUse: 'The quintessential two-seat primary trainer. Low operating costs make it ideal for student solo flights.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Cessna_152_YU-DPN.jpg/1280px-Cessna_152_YU-DPN.jpg',
    imageCredit: 'Wikipedia / Aldo Bidini',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_152',
  },
  {
    id: 'cessna-206-stationair',
    manufacturer: 'Cessna',
    model: '206 Stationair',
    year: 1962,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 300,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 145,
    rangeNm: 795,
    ceilingFt: 15700,
    usefulLoadLbs: 1505,
    fuelCapacityGal: 92,
    burnRateGph: 15,
    certifications: ['VFR', 'IFR', 'Commercial', 'Cargo', 'Night'],
    commonUse: 'The bush pilot\'s freight hauler. Used for cargo, skydiving, floatplane ops, and Alaska/backcountry utility flying.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Cessna_206.jpg/1280px-Cessna_206.jpg',
    imageCredit: 'Wikipedia / Dkroetsch',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_206',
  },
  {
    id: 'piper-pa28-cherokee',
    manufacturer: 'Piper',
    model: 'PA-28 Cherokee',
    year: 1961,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 160,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 117,
    rangeNm: 465,
    ceilingFt: 11000,
    usefulLoadLbs: 785,
    fuelCapacityGal: 50,
    burnRateGph: 8,
    certifications: ['VFR', 'IFR', 'Training', 'Night'],
    commonUse: 'Low-wing alternative to the Cessna 172. Loved by pilots transitioning to complex/retractable aircraft. Stable, forgiving, and classic.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Piper_Cherokee.jpg/1280px-Piper_Cherokee.jpg',
    imageCredit: 'Wikipedia / Greg Goebel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-28_Cherokee',
  },
  {
    id: 'piper-pa28r-arrow',
    manufacturer: 'Piper',
    model: 'PA-28R Arrow',
    year: 1967,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 200,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 138,
    rangeNm: 880,
    ceilingFt: 16800,
    usefulLoadLbs: 836,
    fuelCapacityGal: 72,
    burnRateGph: 10,
    certifications: ['VFR', 'IFR', 'Night', 'Training'],
    commonUse: 'The go-to complex aircraft for commercial certificate candidates. Retractable gear, constant-speed prop, and good IFR capabilities.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Piper_Arrow_III.jpg/1280px-Piper_Arrow_III.jpg',
    imageCredit: 'Wikipedia / Greg Goebel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-28R_Arrow',
  },
  {
    id: 'piper-pa32-saratoga',
    manufacturer: 'Piper',
    model: 'PA-32 Saratoga',
    year: 1979,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 300,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 158,
    rangeNm: 940,
    ceilingFt: 16600,
    usefulLoadLbs: 1175,
    fuelCapacityGal: 107,
    burnRateGph: 14.5,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'High-performance six-seat touring aircraft. Popular for family travel and charter operations.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Piper_Saratoga_SP_II.jpg/1280px-Piper_Saratoga_SP_II.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-32',
  },
  {
    id: 'beechcraft-bonanza-g36',
    manufacturer: 'Beechcraft',
    model: 'Bonanza G36',
    year: 1947,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 300,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 176,
    rangeNm: 915,
    ceilingFt: 18500,
    usefulLoadLbs: 1065,
    fuelCapacityGal: 74,
    burnRateGph: 14,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The "Doctor\'s airplane" — fast, luxurious, and in production for over 75 years. The longest-running aircraft model in history.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Beechcraft_Bonanza_G36.jpg/1280px-Beechcraft_Bonanza_G36.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Beechcraft_Bonanza',
  },
  {
    id: 'cirrus-sr22',
    manufacturer: 'Cirrus',
    model: 'SR22',
    year: 2001,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 310,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 183,
    rangeNm: 1049,
    ceilingFt: 17500,
    usefulLoadLbs: 1119,
    fuelCapacityGal: 92,
    burnRateGph: 16,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'America\'s best-selling GA aircraft. Glass cockpit, CAPS parachute system, and fast cruise speed. The modern pilot\'s touring aircraft.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Cirrus_SR22_N615SR.jpg/1280px-Cirrus_SR22_N615SR.jpg',
    imageCredit: 'Wikipedia / Cirrus Aircraft',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cirrus_SR22',
  },
  {
    id: 'cirrus-sr20',
    manufacturer: 'Cirrus',
    model: 'SR20',
    year: 1999,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 200,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 155,
    rangeNm: 804,
    ceilingFt: 17500,
    usefulLoadLbs: 900,
    fuelCapacityGal: 56,
    burnRateGph: 11,
    certifications: ['VFR', 'IFR', 'Night', 'Training'],
    commonUse: 'The smaller sibling to the SR22. Excellent training aircraft with modern avionics and CAPS parachute.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cirrus_SR20.jpg/1280px-Cirrus_SR20.jpg',
    imageCredit: 'Wikipedia / Cirrus Aircraft',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cirrus_SR20',
  },
  {
    id: 'mooney-m20',
    manufacturer: 'Mooney',
    model: 'M20 Acclaim Ultra',
    year: 1955,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 280,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 242,
    rangeNm: 1250,
    ceilingFt: 25000,
    usefulLoadLbs: 980,
    fuelCapacityGal: 89,
    burnRateGph: 14,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'The fastest piston single. Pilots who need speed and efficiency on long cross-countries choose the Mooney. Its distinctive forward-swept tail is unmistakable.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Mooney_M20_Acclaim_Ultra.jpg/1280px-Mooney_M20_Acclaim_Ultra.jpg',
    imageCredit: 'Wikipedia / RuthAS',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mooney_M20',
  },
  {
    id: 'diamond-da40',
    manufacturer: 'Diamond',
    model: 'DA40 Diamond Star',
    year: 2000,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 180,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 147,
    rangeNm: 720,
    ceilingFt: 16400,
    usefulLoadLbs: 750,
    fuelCapacityGal: 42,
    burnRateGph: 9,
    certifications: ['VFR', 'IFR', 'Training', 'Night'],
    commonUse: 'Austrian-made composite trainer with a T-tail and excellent visibility. Popular at university aviation programs.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Diamond_DA40_D.jpg/1280px-Diamond_DA40_D.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Diamond_DA40',
  },
  {
    id: 'diamond-da20',
    manufacturer: 'Diamond',
    model: 'DA20 Katana',
    year: 1993,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 125,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 128,
    rangeNm: 530,
    ceilingFt: 14000,
    usefulLoadLbs: 530,
    fuelCapacityGal: 24,
    burnRateGph: 6,
    certifications: ['VFR', 'Training'],
    commonUse: 'Sleek two-seat trainer. Side-by-side seating, composite airframe, and sporty handling attract students who want a more dynamic training experience.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Diamond_DA20_C1.jpg/1280px-Diamond_DA20_C1.jpg',
    imageCredit: 'Wikipedia / D. Miller',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Diamond_DA20',
  },
  {
    id: 'grumman-aa5-tiger',
    manufacturer: 'Grumman American',
    model: 'AA-5 Tiger',
    year: 1975,
    category: 'SE',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 150,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 130,
    rangeNm: 580,
    ceilingFt: 13800,
    usefulLoadLbs: 730,
    fuelCapacityGal: 52,
    burnRateGph: 8,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'Fun, sporty four-seater with a sliding canopy. The Tiger has a loyal following for its handling and distinctive looks.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Grumman_AA-5_Tiger.jpg/1280px-Grumman_AA-5_Tiger.jpg',
    imageCredit: 'Wikipedia / Greg Goebel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Grumman_American_AA-5',
  },

  // ── MULTI ENGINE PISTON ────────────────────────────────────────────────────
  {
    id: 'piper-pa44-seminole',
    manufacturer: 'Piper',
    model: 'PA-44 Seminole',
    year: 1978,
    category: 'ME',
    engineType: 'Piston',
    engineCount: 2,
    horsepower: 360,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 160,
    rangeNm: 820,
    ceilingFt: 17100,
    usefulLoadLbs: 1100,
    fuelCapacityGal: 110,
    burnRateGph: 18,
    certifications: ['VFR', 'IFR', 'Training', 'Night'],
    commonUse: 'The most common multi-engine trainer. Counter-rotating props eliminate critical engine concerns, making it ideal for initial MEI training.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Piper_PA-44_Seminole.jpg/1280px-Piper_PA-44_Seminole.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-44_Seminole',
  },
  {
    id: 'beechcraft-baron-58',
    manufacturer: 'Beechcraft',
    model: 'Baron 58',
    year: 1969,
    category: 'ME',
    engineType: 'Piston',
    engineCount: 2,
    horsepower: 600,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 202,
    rangeNm: 1195,
    ceilingFt: 20688,
    usefulLoadLbs: 1625,
    fuelCapacityGal: 166,
    burnRateGph: 26,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The gold standard of piston twins. Fast, capable, and prestigious. Used for charter, cargo, and serious cross-country travel.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Beechcraft_Baron_58_G-BNLZ.jpg/1280px-Beechcraft_Baron_58_G-BNLZ.jpg',
    imageCredit: 'Wikipedia / Alan Wilson',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Beechcraft_Baron',
  },
  {
    id: 'cessna-310',
    manufacturer: 'Cessna',
    model: '310',
    year: 1954,
    category: 'ME',
    engineType: 'Piston',
    engineCount: 2,
    horsepower: 520,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 188,
    rangeNm: 1005,
    ceilingFt: 19750,
    usefulLoadLbs: 1560,
    fuelCapacityGal: 163,
    burnRateGph: 24,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'Classic mid-century twin. Sleek, fast, and capable. Many are still flying on charter and business missions.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Cessna_310.jpg/1280px-Cessna_310.jpg',
    imageCredit: 'Wikipedia / Greg Goebel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_310',
  },
  {
    id: 'piper-aztec',
    manufacturer: 'Piper',
    model: 'PA-23 Aztec',
    year: 1959,
    category: 'ME',
    engineType: 'Piston',
    engineCount: 2,
    horsepower: 500,
    fuelType: '100LL',
    seatsTotal: 6,
    cruiseSpeedKts: 170,
    rangeNm: 920,
    ceilingFt: 21200,
    usefulLoadLbs: 1605,
    fuelCapacityGal: 144,
    burnRateGph: 22,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'Rugged, reliable twin used extensively in commuter and bush operations. High useful load makes it a favorite for cargo and charter.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Piper_Aztec.jpg/1280px-Piper_Aztec.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-23',
  },

  // ── TURBOPROP ─────────────────────────────────────────────────────────────
  {
    id: 'pilatus-pc12',
    manufacturer: 'Pilatus',
    model: 'PC-12 NGX',
    year: 1994,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 1200,
    fuelType: 'JetA',
    seatsTotal: 9,
    cruiseSpeedKts: 285,
    rangeNm: 1803,
    ceilingFt: 30000,
    usefulLoadLbs: 3748,
    fuelCapacityGal: 402,
    burnRateGph: 55,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial', 'Cargo'],
    commonUse: 'The Swiss Army knife of aviation. Single-engine turboprop capable of unpaved strips, IFR flight, cargo, and premium passenger transport.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pilatus_PC-12_NG.jpg/1280px-Pilatus_PC-12_NG.jpg',
    imageCredit: 'Wikipedia / Thierry Weber',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pilatus_PC-12',
  },
  {
    id: 'tbm940',
    manufacturer: 'Daher',
    model: 'TBM 940',
    year: 2019,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 850,
    fuelType: 'JetA',
    seatsTotal: 6,
    cruiseSpeedKts: 330,
    rangeNm: 1730,
    ceilingFt: 31000,
    usefulLoadLbs: 2315,
    fuelCapacityGal: 289,
    burnRateGph: 50,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The fastest single-engine turboprop in production. Connects cities at near-jet speeds with single-pilot capability. Packed with automation.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/TBM-940.jpg/1280px-TBM-940.jpg',
    imageCredit: 'Wikipedia / Daher',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Socata_TBM_900',
  },
  {
    id: 'piper-meridian',
    manufacturer: 'Piper',
    model: 'M500',
    year: 2000,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 500,
    fuelType: 'JetA',
    seatsTotal: 6,
    cruiseSpeedKts: 260,
    rangeNm: 1000,
    ceilingFt: 30000,
    usefulLoadLbs: 1200,
    fuelCapacityGal: 170,
    burnRateGph: 40,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The "step-up" turboprop for GA pilots. Familiar Piper lineage with turbine performance and pressurized cabin.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Piper_Meridian_PA-46-500TP.jpg/1280px-Piper_Meridian_PA-46-500TP.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Piper_PA-46',
  },
  {
    id: 'king-air-c90',
    manufacturer: 'Beechcraft',
    model: 'King Air C90',
    year: 1964,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 2,
    horsepower: 1140,
    fuelType: 'JetA',
    seatsTotal: 9,
    cruiseSpeedKts: 248,
    rangeNm: 1050,
    ceilingFt: 30000,
    usefulLoadLbs: 3000,
    fuelCapacityGal: 384,
    burnRateGph: 80,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial', 'Cargo'],
    commonUse: 'The iconic twin-engine turboprop. Used everywhere from regional charter to medevac to air taxi. Over 7,000 built and still in production.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Beechcraft_King_Air_C90.jpg/1280px-Beechcraft_King_Air_C90.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Beechcraft_King_Air',
  },
  {
    id: 'king-air-350',
    manufacturer: 'Beechcraft',
    model: 'King Air 350',
    year: 1988,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 2,
    horsepower: 2800,
    fuelType: 'JetA',
    seatsTotal: 11,
    cruiseSpeedKts: 310,
    rangeNm: 1806,
    ceilingFt: 35000,
    usefulLoadLbs: 5400,
    fuelCapacityGal: 544,
    burnRateGph: 110,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial', 'Cargo'],
    commonUse: 'The premier light turboprop airliner. Charter, cargo, and government utility flying. Faster and larger than its King Air siblings.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Beechcraft_King_Air_350.jpg/1280px-Beechcraft_King_Air_350.jpg',
    imageCredit: 'Wikipedia / Clem Tillier',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Beechcraft_King_Air',
  },
  {
    id: 'quest-kodiak',
    manufacturer: 'Quest',
    model: 'Kodiak 100',
    year: 2007,
    category: 'Turboprop',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 750,
    fuelType: 'JetA',
    seatsTotal: 10,
    cruiseSpeedKts: 185,
    rangeNm: 1132,
    ceilingFt: 25000,
    usefulLoadLbs: 3530,
    fuelCapacityGal: 335,
    burnRateGph: 45,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial', 'Cargo'],
    commonUse: 'Purpose-built for mission aviation and remote access. Short-field beast used in Alaska, Papua New Guinea, and developing world cargo ops.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Quest_Kodiak_100.jpg/1280px-Quest_Kodiak_100.jpg',
    imageCredit: 'Wikipedia / Mattes',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Quest_Kodiak',
  },

  // ── JETS ──────────────────────────────────────────────────────────────────
  {
    id: 'cirrus-vision-sf50',
    manufacturer: 'Cirrus',
    model: 'Vision Jet SF50',
    year: 2016,
    category: 'Jet',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: null,
    fuelType: 'JetA',
    seatsTotal: 7,
    cruiseSpeedKts: 305,
    rangeNm: 1200,
    ceilingFt: 28000,
    usefulLoadLbs: 1850,
    fuelCapacityGal: 295,
    burnRateGph: 60,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'The world\'s first single-engine personal jet. Equipped with CAPS whole-aircraft parachute. Bridges the gap between piston singles and light jets.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Cirrus_Vision_Jet_SF50.jpg/1280px-Cirrus_Vision_Jet_SF50.jpg',
    imageCredit: 'Wikipedia / Cirrus Aircraft',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cirrus_Vision_SF50',
  },
  {
    id: 'cessna-citation-cj3',
    manufacturer: 'Cessna',
    model: 'Citation CJ3+',
    year: 2004,
    category: 'Jet',
    engineType: 'Turbine',
    engineCount: 2,
    horsepower: null,
    fuelType: 'JetA',
    seatsTotal: 7,
    cruiseSpeedKts: 416,
    rangeNm: 2040,
    ceilingFt: 45000,
    usefulLoadLbs: 3590,
    fuelCapacityGal: 698,
    burnRateGph: 140,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'Light jet workhorse for charter operators and corporate flight departments. Single-pilot certified up to FL450.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Cessna_Citation_CJ3.jpg/1280px-Cessna_Citation_CJ3.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cessna_CitationJet/M2',
  },
  {
    id: 'embraer-phenom-100',
    manufacturer: 'Embraer',
    model: 'Phenom 100EV',
    year: 2008,
    category: 'Jet',
    engineType: 'Turbine',
    engineCount: 2,
    horsepower: null,
    fuelType: 'JetA',
    seatsTotal: 6,
    cruiseSpeedKts: 390,
    rangeNm: 1178,
    ceilingFt: 41000,
    usefulLoadLbs: 2800,
    fuelCapacityGal: 498,
    burnRateGph: 120,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'Brazilian-built very light jet. Popular for owner-operators and small charter fleets. Stand-up cabin and excellent short-field performance.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Embraer_Phenom_100.jpg/1280px-Embraer_Phenom_100.jpg',
    imageCredit: 'Wikipedia / Embraer',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Embraer_Phenom_100',
  },
  {
    id: 'honda-ha420',
    manufacturer: 'Honda Aircraft',
    model: 'HondaJet Elite II',
    year: 2015,
    category: 'Jet',
    engineType: 'Turbine',
    engineCount: 2,
    horsepower: null,
    fuelType: 'JetA',
    seatsTotal: 6,
    cruiseSpeedKts: 422,
    rangeNm: 1547,
    ceilingFt: 43000,
    usefulLoadLbs: 2964,
    fuelCapacityGal: 530,
    burnRateGph: 130,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The most fuel-efficient jet in its class. Honda\'s over-the-wing engine mount design is unique — maximizes cabin space and reduces drag.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/HondaJet_Elite.jpg/1280px-HondaJet_Elite.jpg',
    imageCredit: 'Wikipedia / Honda Aircraft Company',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Honda_HA-420_HondaJet',
  },

  // ── HELICOPTER ────────────────────────────────────────────────────────────
  {
    id: 'robinson-r22',
    manufacturer: 'Robinson',
    model: 'R22 Beta II',
    year: 1979,
    category: 'Helicopter',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 131,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 97,
    rangeNm: 190,
    ceilingFt: 14000,
    usefulLoadLbs: 500,
    fuelCapacityGal: 19,
    burnRateGph: 8,
    certifications: ['VFR', 'Training'],
    commonUse: 'The world\'s most popular training helicopter. Low cost, simple systems, and two-seat layout make it the entry point for most civilian helicopter pilots.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Robinson_R22_Beta_II.jpg/1280px-Robinson_R22_Beta_II.jpg',
    imageCredit: 'Wikipedia / Kogo',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robinson_R22',
  },
  {
    id: 'robinson-r44',
    manufacturer: 'Robinson',
    model: 'R44 Raven II',
    year: 1992,
    category: 'Helicopter',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 260,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 113,
    rangeNm: 300,
    ceilingFt: 14000,
    usefulLoadLbs: 1100,
    fuelCapacityGal: 50,
    burnRateGph: 14,
    certifications: ['VFR', 'Night', 'Training', 'Commercial'],
    commonUse: 'The most popular four-seat helicopter in the world. Used for tours, photography, news gathering, and personal transport.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Robinson_R44_Raven_II_N464WT.jpg/1280px-Robinson_R44_Raven_II_N464WT.jpg',
    imageCredit: 'Wikipedia / Kaboldy',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robinson_R44',
  },
  {
    id: 'bell-206-jetranger',
    manufacturer: 'Bell',
    model: '206 JetRanger III',
    year: 1962,
    category: 'Helicopter',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 420,
    fuelType: 'JetA',
    seatsTotal: 5,
    cruiseSpeedKts: 115,
    rangeNm: 380,
    ceilingFt: 20000,
    usefulLoadLbs: 1455,
    fuelCapacityGal: 76,
    burnRateGph: 22,
    certifications: ['VFR', 'IFR', 'Night', 'Commercial'],
    commonUse: 'The helicopter that defined a generation. EMS, law enforcement, news gathering, oil & gas, and tours — the JetRanger has done it all.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Bell_206_JetRanger.jpg/1280px-Bell_206_JetRanger.jpg',
    imageCredit: 'Wikipedia / Ahunt',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bell_206',
  },
  {
    id: 'robinson-r66',
    manufacturer: 'Robinson',
    model: 'R66 Turbine',
    year: 2010,
    category: 'Helicopter',
    engineType: 'Turbine',
    engineCount: 1,
    horsepower: 300,
    fuelType: 'JetA',
    seatsTotal: 5,
    cruiseSpeedKts: 120,
    rangeNm: 350,
    ceilingFt: 14000,
    usefulLoadLbs: 1340,
    fuelCapacityGal: 73,
    burnRateGph: 18,
    certifications: ['VFR', 'Night', 'Commercial'],
    commonUse: 'Robinson\'s turbine model. Better high-altitude performance than the R44, lighter on JetA, and popular for tours and utility work.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Robinson_R66.jpg/1280px-Robinson_R66.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Robinson_R66',
  },

  // ── LSA (LIGHT SPORT AIRCRAFT) ─────────────────────────────────────────────
  {
    id: 'czech-sport-aircraft-ps28',
    manufacturer: 'Czech Sport Aircraft',
    model: 'SportCruiser PS-28',
    year: 2006,
    category: 'LSA',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 100,
    fuelType: 'MOGAS',
    seatsTotal: 2,
    cruiseSpeedKts: 120,
    rangeNm: 615,
    ceilingFt: 14000,
    usefulLoadLbs: 485,
    fuelCapacityGal: 32,
    burnRateGph: 5,
    certifications: ['VFR'],
    commonUse: 'Popular Czech-designed LSA. Glass cockpit and modern looks at a lower price point. Great for Sport Pilot certificate holders.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Czech_Sport_Aircraft_SportCruiser.jpg/1280px-Czech_Sport_Aircraft_SportCruiser.jpg',
    imageCredit: 'Wikipedia / Arpingstone',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Czech_Sport_Aircraft_SportCruiser',
  },
  {
    id: 'pipistrel-alpha-trainer',
    manufacturer: 'Pipistrel',
    model: 'Alpha Trainer',
    year: 2010,
    category: 'LSA',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 100,
    fuelType: 'MOGAS',
    seatsTotal: 2,
    cruiseSpeedKts: 104,
    rangeNm: 540,
    ceilingFt: 13000,
    usefulLoadLbs: 426,
    fuelCapacityGal: 30,
    burnRateGph: 4.5,
    certifications: ['VFR', 'Training'],
    commonUse: 'Slovenian LSA known for fuel efficiency and composite construction. Used by many training academies as a cost-effective primary trainer.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Pipistrel_Alpha_Trainer.jpg/1280px-Pipistrel_Alpha_Trainer.jpg',
    imageCredit: 'Wikipedia / Pipistrel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pipistrel_Alpha',
  },
  {
    id: 'icon-a5',
    manufacturer: 'ICON Aircraft',
    model: 'A5',
    year: 2015,
    category: 'LSA',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 100,
    fuelType: 'MOGAS',
    seatsTotal: 2,
    cruiseSpeedKts: 95,
    rangeNm: 427,
    ceilingFt: 10000,
    usefulLoadLbs: 430,
    fuelCapacityGal: 20,
    burnRateGph: 5,
    certifications: ['VFR'],
    commonUse: 'The recreational aviation dream — an amphibious LSA that can take off and land on water or pavement. Designed to appeal to non-pilots.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/ICON_Aircraft_A5.jpg/1280px-ICON_Aircraft_A5.jpg',
    imageCredit: 'Wikipedia / ICON Aircraft',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Icon_A5',
  },
  {
    id: 'pipistrel-velis-electro',
    manufacturer: 'Pipistrel',
    model: 'Velis Electro',
    year: 2020,
    category: 'LSA',
    engineType: 'Electric',
    engineCount: 1,
    horsepower: 57,
    fuelType: 'Electric',
    seatsTotal: 2,
    cruiseSpeedKts: 92,
    rangeNm: 55,
    ceilingFt: 12000,
    usefulLoadLbs: 342,
    fuelCapacityGal: null,
    burnRateGph: null,
    certifications: ['VFR', 'Training'],
    commonUse: 'The world\'s first type-certified electric aircraft. Being adopted by flight schools in Europe. 50-minute endurance makes it practical for local training.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Pipistrel_Velis_Electro.jpg/1280px-Pipistrel_Velis_Electro.jpg',
    imageCredit: 'Wikipedia / Pipistrel',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pipistrel_Velis_Electro',
  },

  // ── EXPERIMENTAL / WARBIRDS ───────────────────────────────────────────────
  {
    id: 'vans-rv7',
    manufacturer: "Van's Aircraft",
    model: 'RV-7',
    year: 2001,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 180,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 185,
    rangeNm: 800,
    ceilingFt: 18000,
    usefulLoadLbs: 700,
    fuelCapacityGal: 42,
    burnRateGph: 9,
    certifications: ['VFR', 'Aerobatic'],
    commonUse: 'The most popular experimental kit aircraft ever built. Aerobatic, fast, and fun. Beloved by sport pilots who want to build their own airplane.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Vans_RV-7.jpg/1280px-Vans_RV-7.jpg',
    imageCredit: "Wikipedia / Van's Aircraft",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Van%27s_RV-7",
  },
  {
    id: 'vans-rv10',
    manufacturer: "Van's Aircraft",
    model: 'RV-10',
    year: 2003,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 260,
    fuelType: '100LL',
    seatsTotal: 4,
    cruiseSpeedKts: 178,
    rangeNm: 1000,
    ceilingFt: 16000,
    usefulLoadLbs: 1000,
    fuelCapacityGal: 60,
    burnRateGph: 12,
    certifications: ['VFR', 'IFR', 'Night'],
    commonUse: 'Four-seat family tourer you build yourself. Cross-country capability of a certified aircraft at a fraction of the cost.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Vans_RV-10.jpg/1280px-Vans_RV-10.jpg',
    imageCredit: "Wikipedia / Van's Aircraft",
    wikipediaUrl: "https://en.wikipedia.org/wiki/Van%27s_RV-10",
  },
  {
    id: 'north-american-t6-texan',
    manufacturer: 'North American',
    model: 'T-6 Texan',
    year: 1938,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 600,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 145,
    rangeNm: 730,
    ceilingFt: 24200,
    usefulLoadLbs: 900,
    fuelCapacityGal: 110,
    burnRateGph: 30,
    certifications: ['VFR', 'Aerobatic'],
    commonUse: 'The "Harvard" that trained WWII pilots of every Allied nation. Now flown at airshows and by warbird collectors worldwide.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/North_American_T-6_Texan.jpg/1280px-North_American_T-6_Texan.jpg',
    imageCredit: 'Wikipedia / USAF',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/North_American_T-6_Texan',
  },
  {
    id: 'supermarine-spitfire',
    manufacturer: 'Supermarine',
    model: 'Spitfire Mk IX',
    year: 1936,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 1720,
    fuelType: '100LL',
    seatsTotal: 1,
    cruiseSpeedKts: 310,
    rangeNm: 410,
    ceilingFt: 43000,
    usefulLoadLbs: 800,
    fuelCapacityGal: 85,
    burnRateGph: 60,
    certifications: ['VFR', 'Aerobatic'],
    commonUse: 'The legendary Battle of Britain fighter. Fewer than 80 remain airworthy worldwide — each flight is a living piece of history.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Supermarine_Spitfire_Mk_Ia.jpg/1280px-Supermarine_Spitfire_Mk_Ia.jpg',
    imageCredit: 'Wikipedia / Kogo',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Supermarine_Spitfire',
  },
  {
    id: 'north-american-p51-mustang',
    manufacturer: 'North American',
    model: 'P-51D Mustang',
    year: 1940,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 1695,
    fuelType: '100LL',
    seatsTotal: 1,
    cruiseSpeedKts: 310,
    rangeNm: 1000,
    ceilingFt: 41900,
    usefulLoadLbs: 1270,
    fuelCapacityGal: 184,
    burnRateGph: 55,
    certifications: ['VFR', 'Aerobatic'],
    commonUse: 'The long-range escort fighter that helped win WWII. Airshow icon and the holy grail for warbird collectors.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/North_American_P-51D_Mustang.jpg/1280px-North_American_P-51D_Mustang.jpg',
    imageCredit: 'Wikipedia / U.S. Air Force',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/North_American_P-51_Mustang',
  },
  {
    id: 'stearman-pt17',
    manufacturer: 'Boeing',
    model: 'Stearman PT-17 Kaydet',
    year: 1934,
    category: 'Experimental',
    engineType: 'Piston',
    engineCount: 1,
    horsepower: 220,
    fuelType: '100LL',
    seatsTotal: 2,
    cruiseSpeedKts: 106,
    rangeNm: 505,
    ceilingFt: 13200,
    usefulLoadLbs: 640,
    fuelCapacityGal: 46,
    burnRateGph: 15,
    certifications: ['VFR', 'Aerobatic'],
    commonUse: 'Open-cockpit biplane used to train 75% of US WWII pilots. Now beloved by vintage aircraft enthusiasts and barnstormers.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Boeing_Stearman_PT-17.jpg/1280px-Boeing_Stearman_PT-17.jpg',
    imageCredit: 'Wikipedia / Peter Bakema',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stearman_Aircraft',
  },
]

export function getAircraftById(id: string): AircraftEntry | undefined {
  return aircraftDatabase.find(a => a.id === id)
}

export function getAircraftByCategory(category: AircraftEntry['category']): AircraftEntry[] {
  return aircraftDatabase.filter(a => a.category === category)
}

export function searchAircraft(query: string): AircraftEntry[] {
  const q = query.toLowerCase()
  return aircraftDatabase.filter(
    a =>
      a.manufacturer.toLowerCase().includes(q) ||
      a.model.toLowerCase().includes(q) ||
      a.commonUse.toLowerCase().includes(q),
  )
}
