export interface CuratedRoute {
  id: string
  stateCode: string
  region: 'West' | 'Midwest' | 'South' | 'Northeast'
  name: string
  description: string
  waypoints: { icao: string; name: string; lat: number; lon: number }[]
  distanceNm: number
  aircraftCategory: 'SE' | 'ME' | 'Turboprop' | 'Helicopter' | 'Any'
  tags: ('scenic' | 'training' | 'cross-country' | 'coastal' | 'mountain' | 'urban' | 'island' | 'desert' | 'historical')[]
  imageUrl: string
  imageCredit: string
}

export const curatedRoutes: CuratedRoute[] = [
  // ── CALIFORNIA ──────────────────────────────────────────────────────────────
  {
    id: 'ca-bay-tour',
    stateCode: 'CA',
    region: 'West',
    name: 'San Francisco Bay Tour',
    description: 'Classic Bay Area VFR tour from San Carlos over the Golden Gate, Half Moon Bay, and down the coast to Watsonville. Spectacular views of the bridge, Alcatraz, and the Pacific coastline.',
    waypoints: [
      { icao: 'KSQL', name: 'San Carlos', lat: 37.5119, lon: -122.2499 },
      { icao: 'KHAF', name: 'Half Moon Bay', lat: 37.5134, lon: -122.5007 },
      { icao: 'KWVI', name: 'Watsonville', lat: 36.9357, lon: -121.7897 },
      { icao: 'KSNS', name: 'Salinas', lat: 36.6628, lon: -121.6062 },
    ],
    distanceNm: 72,
    aircraftCategory: 'SE',
    tags: ['scenic', 'coastal', 'urban'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/GoldenGateBridge-001.jpg/1280px-GoldenGateBridge-001.jpg',
    imageCredit: 'Wikipedia / Rich Niewiroski Jr.',
  },
  {
    id: 'ca-la-basin',
    stateCode: 'CA',
    region: 'West',
    name: 'Los Angeles Basin Cruise',
    description: 'Fly the iconic LA coastal corridor from Van Nuys over Santa Monica, the South Bay, and finish at Orange County. Keep an eye out for the Hollywood Sign on departure.',
    waypoints: [
      { icao: 'KVNY', name: 'Van Nuys', lat: 34.2098, lon: -118.4896 },
      { icao: 'KSMO', name: 'Santa Monica', lat: 34.0158, lon: -118.4508 },
      { icao: 'KTOA', name: 'Torrance', lat: 33.8034, lon: -118.3396 },
      { icao: 'KFUL', name: 'Fullerton', lat: 33.8720, lon: -117.9799 },
      { icao: 'KSNA', name: 'Orange County', lat: 33.6757, lon: -117.8682 },
    ],
    distanceNm: 58,
    aircraftCategory: 'SE',
    tags: ['urban', 'coastal', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Los_Angeles_CA.jpg/1280px-Los_Angeles_CA.jpg',
    imageCredit: 'Wikipedia / Thomas Pintaric',
  },
  {
    id: 'ca-yosemite',
    stateCode: 'CA',
    region: 'West',
    name: 'Yosemite Valley Approach',
    description: 'Fly from Modesto into the Sierra Nevada foothills and approach the dramatic Yosemite Valley corridor. Stunning views of El Capitan and Half Dome from altitude.',
    waypoints: [
      { icao: 'KMOD', name: 'Modesto', lat: 37.6258, lon: -120.9544 },
      { icao: 'KMCE', name: 'Merced', lat: 37.2847, lon: -120.5138 },
      { icao: 'KMMH', name: 'Mammoth Lakes', lat: 37.6241, lon: -118.8376 },
    ],
    distanceNm: 118,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg/1280px-Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg',
    imageCredit: 'Wikipedia / Diliff',
  },
  {
    id: 'ca-wine-country',
    stateCode: 'CA',
    region: 'West',
    name: 'Wine Country Loop',
    description: 'Circle Sonoma and Napa wine country from Santa Rosa, flying over rolling vineyard-covered hills and the majestic San Pablo Bay.',
    waypoints: [
      { icao: 'KSTS', name: 'Santa Rosa', lat: 38.5090, lon: -122.8129 },
      { icao: 'O69', name: 'Petaluma', lat: 38.2571, lon: -122.6084 },
      { icao: 'KAPC', name: 'Napa County', lat: 38.2132, lon: -122.2807 },
      { icao: 'KOAK', name: 'Oakland', lat: 37.7213, lon: -122.2208 },
    ],
    distanceNm: 64,
    aircraftCategory: 'SE',
    tags: ['scenic', 'training', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Napa_Valley_from_the_air.jpg/1280px-Napa_Valley_from_the_air.jpg',
    imageCredit: 'Wikipedia / Jon Sullivan',
  },
  {
    id: 'ca-big-sur',
    stateCode: 'CA',
    region: 'West',
    name: 'Big Sur Coastal Highway',
    description: 'One of California\'s most breathtaking aerial routes — fly the Big Sur coastline from Santa Maria north to Santa Barbara. The dramatic cliffs meet the Pacific 500 feet below.',
    waypoints: [
      { icao: 'KSMX', name: 'Santa Maria', lat: 34.8996, lon: -120.4575 },
      { icao: 'KSBA', name: 'Santa Barbara', lat: 34.4262, lon: -119.8400 },
      { icao: 'KCMA', name: 'Camarillo', lat: 34.2137, lon: -119.0944 },
    ],
    distanceNm: 95,
    aircraftCategory: 'SE',
    tags: ['coastal', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Big_Sur_%285748537908%29.jpg/1280px-Big_Sur_%285748537908%29.jpg',
    imageCredit: 'Wikipedia / Frank Schulenburg',
  },

  // ── TEXAS ───────────────────────────────────────────────────────────────────
  {
    id: 'tx-hill-country',
    stateCode: 'TX',
    region: 'South',
    name: 'Texas Hill Country Loop',
    description: 'Fly through the rolling cedar-covered hills of the Texas Hill Country. Charming small airports, wildflower meadows below in spring, and the Pedernales River winding beneath you.',
    waypoints: [
      { icao: 'KAUS', name: 'Austin-Bergstrom', lat: 30.1975, lon: -97.6699 },
      { icao: 'KGTU', name: 'Georgetown', lat: 30.6788, lon: -97.6794 },
      { icao: '3R9', name: 'Llano', lat: 30.7846, lon: -98.6627 },
      { icao: 'KSAT', name: 'San Antonio', lat: 29.5337, lon: -98.4698 },
    ],
    distanceNm: 140,
    aircraftCategory: 'SE',
    tags: ['scenic', 'cross-country', 'training'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Texas_Hill_Country.jpg/1280px-Texas_Hill_Country.jpg',
    imageCredit: 'Wikipedia / Billy Hathorn',
  },
  {
    id: 'tx-big-bend',
    stateCode: 'TX',
    region: 'South',
    name: 'Big Bend Desert Circuit',
    description: 'Cross the stark and beautiful Chihuahuan Desert to the dramatic canyons of Big Bend. Ridgelines and the Rio Grande come into view as you approach the border.',
    waypoints: [
      { icao: 'KMAF', name: 'Midland', lat: 31.9425, lon: -102.2019 },
      { icao: 'KPKV', name: 'Pecos', lat: 31.3825, lon: -103.5113 },
      { icao: 'KFST', name: 'Fort Stockton', lat: 30.9158, lon: -102.9161 },
      { icao: 'KBIF', name: 'El Paso Biggs', lat: 31.8499, lon: -106.3798 },
    ],
    distanceNm: 185,
    aircraftCategory: 'SE',
    tags: ['desert', 'cross-country', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Big_Bend_NP_Color.jpg/1280px-Big_Bend_NP_Color.jpg',
    imageCredit: 'Wikipedia / Wing-Chi Poon',
  },
  {
    id: 'tx-gulf-coast',
    stateCode: 'TX',
    region: 'South',
    name: 'Texas Gulf Coast Run',
    description: 'Skim the Gulf Coast from Houston Hobby east to Beaumont, crossing barrier islands, bays, and petrochemical skylines that define coastal Texas.',
    waypoints: [
      { icao: 'KHOU', name: 'Houston Hobby', lat: 29.6454, lon: -95.2789 },
      { icao: 'KLBX', name: 'Brazoria', lat: 29.1086, lon: -95.4623 },
      { icao: 'KBPT', name: 'Beaumont', lat: 29.9508, lon: -94.0207 },
    ],
    distanceNm: 78,
    aircraftCategory: 'SE',
    tags: ['coastal', 'cross-country', 'urban'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Galveston_beach.jpg/1280px-Galveston_beach.jpg',
    imageCredit: 'Wikipedia / Daniel Mayer',
  },
  {
    id: 'tx-dfw-metroplex',
    stateCode: 'TX',
    region: 'South',
    name: 'DFW Metroplex Tour',
    description: 'Explore the Dallas-Fort Worth Metroplex from the air — Love Field to Spinks, Fort Worth\'s reliever airports, and the sprawling Alliance commercial corridor.',
    waypoints: [
      { icao: 'KDAL', name: 'Dallas Love Field', lat: 32.8471, lon: -96.8518 },
      { icao: 'KFWS', name: 'Fort Worth Spinks', lat: 32.5699, lon: -97.3082 },
      { icao: 'KGPM', name: 'Grand Prairie', lat: 32.6988, lon: -97.0461 },
      { icao: 'KAFW', name: 'Alliance Fort Worth', lat: 32.9876, lon: -97.3188 },
    ],
    distanceNm: 66,
    aircraftCategory: 'SE',
    tags: ['urban', 'training', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dallas_skyline_2018.jpg/1280px-Dallas_skyline_2018.jpg',
    imageCredit: 'Wikipedia / Cburnett',
  },

  // ── FLORIDA ─────────────────────────────────────────────────────────────────
  {
    id: 'fl-florida-keys',
    stateCode: 'FL',
    region: 'South',
    name: 'Florida Keys Island Hop',
    description: 'The ultimate VFR adventure: island-hop down the Florida Keys following the Overseas Highway, ending at the southernmost point in the continental US — Key West.',
    waypoints: [
      { icao: 'KOPF', name: 'Miami Opa-locka', lat: 25.9070, lon: -80.2784 },
      { icao: 'X51', name: 'Marathon', lat: 24.7261, lon: -81.0514 },
      { icao: 'KEYW', name: 'Key West', lat: 24.5563, lon: -81.7596 },
    ],
    distanceNm: 98,
    aircraftCategory: 'SE',
    tags: ['coastal', 'island', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Florida_Keys_aerial.jpg/1280px-Florida_Keys_aerial.jpg',
    imageCredit: 'Wikipedia / Michael Rivera',
  },
  {
    id: 'fl-space-coast',
    stateCode: 'FL',
    region: 'South',
    name: 'Space Coast Explorer',
    description: 'Fly the Atlantic coast from Orlando Executive past Kennedy Space Center and the Vehicle Assembly Building. On clear days, you can spot rockets on the launch pads.',
    waypoints: [
      { icao: 'KORL', name: 'Orlando Executive', lat: 28.5455, lon: -81.3329 },
      { icao: 'KTIX', name: 'Titusville', lat: 28.5148, lon: -80.7992 },
      { icao: 'KISM', name: 'Kissimmee', lat: 28.2898, lon: -81.4371 },
    ],
    distanceNm: 85,
    aircraftCategory: 'SE',
    tags: ['coastal', 'historical', 'urban'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/KSC-Launch-Complex-39.jpg/1280px-KSC-Launch-Complex-39.jpg',
    imageCredit: 'Wikipedia / NASA',
  },
  {
    id: 'fl-everglades',
    stateCode: 'FL',
    region: 'South',
    name: 'Everglades River of Grass',
    description: 'Fly west from Fort Lauderdale over the vast sawgrass prairies of the Everglades. Spot alligators, wading birds, and mangrove islands from your cockpit.',
    waypoints: [
      { icao: 'KFXE', name: 'Fort Lauderdale Executive', lat: 26.1973, lon: -80.1707 },
      { icao: 'KHST', name: 'Homestead ARB', lat: 25.4886, lon: -80.3856 },
      { icao: 'X06', name: 'Everglades City', lat: 25.8559, lon: -81.3929 },
    ],
    distanceNm: 90,
    aircraftCategory: 'SE',
    tags: ['scenic', 'coastal', 'island'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Everglades_National_Park.jpg/1280px-Everglades_National_Park.jpg',
    imageCredit: 'Wikipedia / United States Geological Survey',
  },
  {
    id: 'fl-panhandle',
    stateCode: 'FL',
    region: 'South',
    name: 'Emerald Coast Panhandle',
    description: 'Fly the Emerald Coast — the whitest, most pristine beaches in the US. Route threads past Pensacola NAS, Eglin AFB\'s test range, and the Destin area resorts.',
    waypoints: [
      { icao: 'KPNS', name: 'Pensacola', lat: 30.4734, lon: -87.1866 },
      { icao: 'KVPS', name: 'Destin-Fort Walton', lat: 30.4832, lon: -86.5253 },
      { icao: 'KECP', name: 'NW FL Beaches', lat: 30.3582, lon: -85.7955 },
      { icao: 'KPFN', name: 'Panama City', lat: 30.2121, lon: -85.6828 },
    ],
    distanceNm: 88,
    aircraftCategory: 'SE',
    tags: ['coastal', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Emerald_Coast_Destin.jpg/1280px-Emerald_Coast_Destin.jpg',
    imageCredit: 'Wikipedia / Spyplane',
  },

  // ── ALASKA ──────────────────────────────────────────────────────────────────
  {
    id: 'ak-kenai-peninsula',
    stateCode: 'AK',
    region: 'West',
    name: 'Kenai Peninsula Circuit',
    description: 'Alaska\'s most accessible backcountry flying. Departing Anchorage, follow the fjord-cut coastline of the Kenai Peninsula with glaciers, salmon rivers, and moose below.',
    waypoints: [
      { icao: 'PANC', name: 'Anchorage', lat: 61.1744, lon: -149.9963 },
      { icao: 'PAEN', name: 'Kenai', lat: 60.5731, lon: -151.2450 },
      { icao: 'PASX', name: 'Soldotna', lat: 60.4757, lon: -151.0394 },
      { icao: 'PAWD', name: 'Seward', lat: 60.1274, lon: -149.4187 },
    ],
    distanceNm: 110,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'coastal'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Kenai_Fjords_National_Park.jpg/1280px-Kenai_Fjords_National_Park.jpg',
    imageCredit: 'Wikipedia / National Park Service',
  },
  {
    id: 'ak-inside-passage',
    stateCode: 'AK',
    region: 'West',
    name: 'Southeast Inside Passage',
    description: 'Fly Alaska\'s legendary Inside Passage between Juneau and Ketchikan — a labyrinth of forested islands, tidewater glaciers, and fishing villages unreachable by road.',
    waypoints: [
      { icao: 'PAJN', name: 'Juneau', lat: 58.3550, lon: -134.5763 },
      { icao: 'PAPG', name: 'Petersburg', lat: 56.8018, lon: -132.9453 },
      { icao: 'PAKT', name: 'Ketchikan', lat: 55.3556, lon: -131.7137 },
    ],
    distanceNm: 192,
    aircraftCategory: 'SE',
    tags: ['coastal', 'scenic', 'island', 'mountain'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Inside_Passage_Alaska.jpg/1280px-Inside_Passage_Alaska.jpg',
    imageCredit: 'Wikipedia / Ghee',
  },
  {
    id: 'ak-denali-approach',
    stateCode: 'AK',
    region: 'West',
    name: 'Denali Approach',
    description: 'Fly north from Anchorage up the Susitna Valley with Denali — North America\'s tallest peak at 20,310 ft — dominating the horizon. Stay legal at 11,500 ft MSL for the best view.',
    waypoints: [
      { icao: 'PANC', name: 'Anchorage', lat: 61.1744, lon: -149.9963 },
      { icao: 'PABV', name: 'Birchwood', lat: 61.4166, lon: -149.5074 },
      { icao: 'PANN', name: 'Nenana', lat: 64.5497, lon: -149.0944 },
      { icao: 'PAEI', name: 'Eielson AFB', lat: 64.6657, lon: -147.1019 },
    ],
    distanceNm: 245,
    aircraftCategory: 'ME',
    tags: ['mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Denali_Mt_McKinley.jpg/1280px-Denali_Mt_McKinley.jpg',
    imageCredit: 'Wikipedia / David Broome',
  },

  // ── HAWAII ──────────────────────────────────────────────────────────────────
  {
    id: 'hi-inter-island',
    stateCode: 'HI',
    region: 'West',
    name: 'Hawaiian Island Hop',
    description: 'The classic Hawaii inter-island VFR route. Hop from Honolulu to Maui\'s Kahului, then continue to Kona on the Big Island. Trade winds and volcanic peaks make this unforgettable.',
    waypoints: [
      { icao: 'PHNL', name: 'Honolulu', lat: 21.3187, lon: -157.9225 },
      { icao: 'PHOG', name: 'Kahului (Maui)', lat: 20.8986, lon: -156.4305 },
      { icao: 'PHKO', name: 'Ellison Onizuka Kona', lat: 19.7388, lon: -156.0456 },
    ],
    distanceNm: 174,
    aircraftCategory: 'SE',
    tags: ['island', 'scenic', 'coastal', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Hawaii_-_Waimea_Canyon_%2814185%29.jpg/1280px-Hawaii_-_Waimea_Canyon_%2814185%29.jpg',
    imageCredit: 'Wikipedia / Dhilung Kirat',
  },
  {
    id: 'hi-oahu-circle',
    stateCode: 'HI',
    region: 'West',
    name: 'Oahu Circle Tour',
    description: 'Circle the island of Oahu at 1,500 ft AGL — the Ko\'olau Range on one side, the Pacific on the other. Pass Waikiki, Diamond Head, Pearl Harbor, and the North Shore in one flight.',
    waypoints: [
      { icao: 'PHNL', name: 'Honolulu', lat: 21.3187, lon: -157.9225 },
      { icao: 'PHNA', name: 'Kaneohe/Kailua MCAS', lat: 21.4502, lon: -157.7683 },
      { icao: 'PHDH', name: 'Dillingham', lat: 21.5796, lon: -158.1974 },
    ],
    distanceNm: 62,
    aircraftCategory: 'SE',
    tags: ['island', 'coastal', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Waikiki_Beach_Honolulu_Hawaii.jpg/1280px-Waikiki_Beach_Honolulu_Hawaii.jpg',
    imageCredit: 'Wikipedia / Thomas Pintaric',
  },
  {
    id: 'hi-big-island-volcanoes',
    stateCode: 'HI',
    region: 'West',
    name: 'Big Island Volcano Circuit',
    description: 'Circumnavigate Hawaii\'s Big Island — from Kona\'s dry lava fields across lush Hilo rain forests, over Kilauea\'s summit caldera, and back along the Kohala Coast.',
    waypoints: [
      { icao: 'PHKO', name: 'Kona', lat: 19.7388, lon: -156.0456 },
      { icao: 'PHTO', name: 'Hilo', lat: 19.7214, lon: -155.0484 },
      { icao: 'PHMU', name: 'Waimea-Kohala', lat: 20.0013, lon: -155.6680 },
    ],
    distanceNm: 118,
    aircraftCategory: 'SE',
    tags: ['island', 'scenic', 'mountain'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kilauea_Volcano_Hawaii.jpg/1280px-Kilauea_Volcano_Hawaii.jpg',
    imageCredit: 'Wikipedia / Hawaii Volcano Observatory',
  },

  // ── COLORADO ────────────────────────────────────────────────────────────────
  {
    id: 'co-mountain-passes',
    stateCode: 'CO',
    region: 'West',
    name: 'High Country Mountain Passes',
    description: 'Colorado\'s premier VFR mountain route — but only for experienced pilots. Cross the Continental Divide from Denver to Eagle, down to Aspen, and over Monarch Pass to Gunnison.',
    waypoints: [
      { icao: 'KDEN', name: 'Denver Intl', lat: 39.8561, lon: -104.6737 },
      { icao: 'KEGE', name: 'Eagle/Vail', lat: 39.6426, lon: -106.9177 },
      { icao: 'KASE', name: 'Aspen', lat: 39.2232, lon: -106.8688 },
      { icao: 'KGUC', name: 'Gunnison', lat: 38.5339, lon: -106.9332 },
    ],
    distanceNm: 152,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rocky_mountain_np.jpg/1280px-Rocky_mountain_np.jpg',
    imageCredit: 'Wikipedia / NASA',
  },
  {
    id: 'co-front-range',
    stateCode: 'CO',
    region: 'West',
    name: 'Front Range Corridor',
    description: 'Fly the Front Range from Rocky Mountain Metro south along the Rockies to Colorado Springs and Pueblo. The dramatic escarpment of the Rampart Range looms to the west the entire route.',
    waypoints: [
      { icao: 'KBJC', name: 'Rocky Mountain Metro', lat: 39.9088, lon: -105.1171 },
      { icao: 'KFNL', name: 'Fort Collins', lat: 40.4512, lon: -105.0115 },
      { icao: 'KGXY', name: 'Greeley', lat: 40.4375, lon: -104.6333 },
      { icao: 'KCOS', name: 'Colorado Springs', lat: 38.8059, lon: -104.7008 },
    ],
    distanceNm: 105,
    aircraftCategory: 'SE',
    tags: ['mountain', 'training', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Pikes_Peak_from_Air_Force_Academy.jpg/1280px-Pikes_Peak_from_Air_Force_Academy.jpg',
    imageCredit: 'Wikipedia / Denverjeffrey',
  },
  {
    id: 'co-san-luis-valley',
    stateCode: 'CO',
    region: 'West',
    name: 'San Luis Valley & Great Sand Dunes',
    description: 'The flat San Luis Valley is one of the best beginner high-altitude destinations in Colorado. Fly past the Great Sand Dunes, the world\'s tallest, backed by the 14,000-ft Sangre de Cristo range.',
    waypoints: [
      { icao: 'KCOS', name: 'Colorado Springs', lat: 38.8059, lon: -104.7008 },
      { icao: 'KPUB', name: 'Pueblo', lat: 38.2891, lon: -104.4968 },
      { icao: 'KALS', name: 'Alamosa', lat: 37.4348, lon: -105.8666 },
    ],
    distanceNm: 122,
    aircraftCategory: 'SE',
    tags: ['mountain', 'desert', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Great_Sand_Dunes_NP_USA.jpg/1280px-Great_Sand_Dunes_NP_USA.jpg',
    imageCredit: 'Wikipedia / Kmusser',
  },

  // ── ARIZONA ─────────────────────────────────────────────────────────────────
  {
    id: 'az-grand-canyon',
    stateCode: 'AZ',
    region: 'West',
    name: 'Grand Canyon Rim VFR',
    description: 'The most iconic VFR route in the Southwest. Depart Prescott, cross the Verde Valley, and approach the Grand Canyon from the south rim. Follow the SFRA rules and stay north of the Bright Angel corridor.',
    waypoints: [
      { icao: 'KPRC', name: 'Prescott', lat: 34.6545, lon: -112.4198 },
      { icao: 'KSEZ', name: 'Sedona', lat: 34.8486, lon: -111.7885 },
      { icao: 'KFLG', name: 'Flagstaff', lat: 35.1385, lon: -111.6712 },
      { icao: 'KGCN', name: 'Grand Canyon', lat: 35.9524, lon: -112.1472 },
    ],
    distanceNm: 88,
    aircraftCategory: 'SE',
    tags: ['desert', 'mountain', 'scenic', 'historical'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg/1280px-USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg',
    imageCredit: 'Wikipedia / Luca Galuzzi',
  },
  {
    id: 'az-phoenix-valley',
    stateCode: 'AZ',
    region: 'West',
    name: 'Phoenix Valley Desert Circuit',
    description: 'Circle the greater Phoenix metro area through its ring of reliever airports. The brown desert mountains and dense suburban grid are striking from the air, especially at dusk.',
    waypoints: [
      { icao: 'KPHX', name: 'Phoenix Sky Harbor', lat: 33.4373, lon: -112.0078 },
      { icao: 'KSDL', name: 'Scottsdale', lat: 33.6229, lon: -111.9110 },
      { icao: 'KIWA', name: 'Mesa Gateway', lat: 33.3078, lon: -111.6548 },
      { icao: 'KCHD', name: 'Chandler', lat: 33.2692, lon: -111.8110 },
    ],
    distanceNm: 52,
    aircraftCategory: 'SE',
    tags: ['desert', 'urban', 'training'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Aerial_Phoenix_Arizona.jpg/1280px-Aerial_Phoenix_Arizona.jpg',
    imageCredit: 'Wikipedia / Aaronbrick',
  },
  {
    id: 'az-monument-valley',
    stateCode: 'AZ',
    region: 'West',
    name: 'Monument Valley & Canyon de Chelly',
    description: 'Fly through Navajo Nation airspace to the iconic red sandstone buttes of Monument Valley — possibly the most photographed landscape on Earth.',
    waypoints: [
      { icao: 'KFLG', name: 'Flagstaff', lat: 35.1385, lon: -111.6712 },
      { icao: 'KCGZ', name: 'Casa Grande', lat: 32.9546, lon: -111.7669 },
      { icao: 'KCHB', name: 'Navajo', lat: 36.8057, lon: -110.1883 },
    ],
    distanceNm: 168,
    aircraftCategory: 'SE',
    tags: ['desert', 'scenic', 'historical', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Monument_Valley_Navajo_Tribal_Park_UT.jpg/1280px-Monument_Valley_Navajo_Tribal_Park_UT.jpg',
    imageCredit: 'Wikipedia / Palaceota',
  },

  // ── WASHINGTON ──────────────────────────────────────────────────────────────
  {
    id: 'wa-san-juan-islands',
    stateCode: 'WA',
    region: 'West',
    name: 'San Juan Islands Hop',
    description: 'Jewels of Puget Sound — fly from Boeing Field out to Friday Harbor on San Juan Island, then hop to Orcas Island and north to Bellingham. Orcas, seals, and lush green water below.',
    waypoints: [
      { icao: 'KBFI', name: 'Boeing Field', lat: 47.5300, lon: -122.3019 },
      { icao: 'KFHR', name: 'Friday Harbor', lat: 48.5220, lon: -123.0244 },
      { icao: 'KORS', name: 'Orcas Island', lat: 48.7082, lon: -122.9100 },
      { icao: 'KBLI', name: 'Bellingham', lat: 48.7928, lon: -122.5375 },
    ],
    distanceNm: 98,
    aircraftCategory: 'SE',
    tags: ['island', 'coastal', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/San_Juan_Islands_from_Mount_Constitution.jpg/1280px-San_Juan_Islands_from_Mount_Constitution.jpg',
    imageCredit: 'Wikipedia / Walter Siegmund',
  },
  {
    id: 'wa-mt-rainier',
    stateCode: 'WA',
    region: 'West',
    name: 'Mt. Rainier Circumnavigation',
    description: 'One of the great PNW flights — circle the 14,411-ft Rainier volcano at 12,500 ft MSL. The ice cap, Emmons Glacier, and radial valleys are awe-inspiring from altitude.',
    waypoints: [
      { icao: 'KPWT', name: 'Bremerton', lat: 47.4902, lon: -122.7644 },
      { icao: 'KTIW', name: 'Tacoma Narrows', lat: 47.2679, lon: -122.5779 },
      { icao: 'S50', name: 'Auburn', lat: 47.3278, lon: -122.2280 },
      { icao: 'KRNT', name: 'Renton', lat: 47.4932, lon: -122.2163 },
    ],
    distanceNm: 60,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Mount_Rainier_from_Rainier_Vista.jpg/1280px-Mount_Rainier_from_Rainier_Vista.jpg',
    imageCredit: 'Wikipedia / Joe Mabel',
  },
  {
    id: 'wa-olympic-peninsula',
    stateCode: 'WA',
    region: 'West',
    name: 'Olympic Peninsula Loop',
    description: 'Cross the Puget Sound and explore the Olympic Peninsula — from Port Angeles near the Strait of Juan de Fuca, along the wild Pacific Coast, back to the Cascades.',
    waypoints: [
      { icao: 'KSEA', name: 'Seattle-Tacoma', lat: 47.4502, lon: -122.3088 },
      { icao: 'KCLM', name: 'Port Angeles', lat: 48.1202, lon: -123.5000 },
      { icao: 'KBVS', name: 'Skagit Regional', lat: 48.4709, lon: -122.4200 },
    ],
    distanceNm: 112,
    aircraftCategory: 'SE',
    tags: ['coastal', 'mountain', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Hurricane_Ridge_Olympic_National_Park.jpg/1280px-Hurricane_Ridge_Olympic_National_Park.jpg',
    imageCredit: 'Wikipedia / Walter Siegmund',
  },

  // ── NORTH CAROLINA ──────────────────────────────────────────────────────────
  {
    id: 'nc-outer-banks',
    stateCode: 'NC',
    region: 'South',
    name: 'Outer Banks Beach Run',
    description: 'Fly the Outer Banks barrier islands from the Wright Brothers Memorial at Kitty Hawk south to Ocracoke. Historic beaches, Cape Hatteras Lighthouse, and pristine shoals below.',
    waypoints: [
      { icao: 'KFFA', name: 'First Flight (Kitty Hawk)', lat: 36.0182, lon: -75.6713 },
      { icao: 'KMQI', name: 'Morehead City', lat: 34.7929, lon: -76.6015 },
      { icao: 'KILM', name: 'Wilmington', lat: 34.2706, lon: -77.9026 },
    ],
    distanceNm: 112,
    aircraftCategory: 'SE',
    tags: ['coastal', 'historical', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Cape_Hatteras_Lighthouse.jpg/1280px-Cape_Hatteras_Lighthouse.jpg',
    imageCredit: 'Wikipedia / Michael Barera',
  },
  {
    id: 'nc-blue-ridge',
    stateCode: 'NC',
    region: 'South',
    name: 'Blue Ridge Parkway',
    description: 'Follow the spine of the Blue Ridge Mountains from Asheville east through the foothills. The Parkway\'s gentle curves and fall foliage are legendary from the air.',
    waypoints: [
      { icao: 'KAVL', name: 'Asheville', lat: 35.4362, lon: -82.5419 },
      { icao: 'KMOR', name: 'Morristown (TN)', lat: 36.1794, lon: -83.3755 },
      { icao: 'KJQF', name: 'Concord', lat: 35.3878, lon: -80.7089 },
    ],
    distanceNm: 145,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Blue_Ridge_Parkway_-_October_2012.jpg/1280px-Blue_Ridge_Parkway_-_October_2012.jpg',
    imageCredit: 'Wikipedia / Famartin',
  },
  {
    id: 'nc-piedmont-triangle',
    stateCode: 'NC',
    region: 'South',
    name: 'Research Triangle Corridor',
    description: 'Connect the Research Triangle\'s airports from RDU to Fayetteville and Wilmington — a great instrument currency cross-country through the flat Piedmont tobacco fields.',
    waypoints: [
      { icao: 'KRDU', name: 'Raleigh-Durham', lat: 35.8776, lon: -78.7875 },
      { icao: 'KFAY', name: 'Fayetteville', lat: 34.9912, lon: -78.8804 },
      { icao: 'KILM', name: 'Wilmington', lat: 34.2706, lon: -77.9026 },
    ],
    distanceNm: 118,
    aircraftCategory: 'SE',
    tags: ['training', 'cross-country', 'urban'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NC_Research_Triangle.jpg/1280px-NC_Research_Triangle.jpg',
    imageCredit: 'Wikipedia / Kmusser',
  },

  // ── TENNESSEE ───────────────────────────────────────────────────────────────
  {
    id: 'tn-smoky-mountains',
    stateCode: 'TN',
    region: 'South',
    name: 'Great Smoky Mountains Tour',
    description: 'Fly the ridgelines of Great Smoky Mountains National Park from Knoxville, threading through misty hollows and autumn-color ridges above Gatlinburg and Pigeon Forge.',
    waypoints: [
      { icao: 'KTYS', name: 'Knoxville', lat: 35.8118, lon: -83.9940 },
      { icao: 'KMOR', name: 'Morristown', lat: 36.1794, lon: -83.3755 },
      { icao: 'KCSV', name: 'Crossville', lat: 35.9513, lon: -85.0849 },
    ],
    distanceNm: 88,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'historical'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Sunrise_over_the_Smokies.jpg/1280px-Sunrise_over_the_Smokies.jpg',
    imageCredit: 'Wikipedia / Brian Stansberry',
  },
  {
    id: 'tn-nashville-loop',
    stateCode: 'TN',
    region: 'South',
    name: 'Nashville Music City Loop',
    description: 'Circle Music City from BNA out to the rolling green Tennessee countryside. Reservoir lakes reflect the sky, and Nashville\'s skyline dominates the horizon on return.',
    waypoints: [
      { icao: 'KBNA', name: 'Nashville', lat: 36.1245, lon: -86.6782 },
      { icao: 'KMKL', name: 'Jackson', lat: 35.5999, lon: -88.9157 },
      { icao: 'KCSV', name: 'Crossville', lat: 35.9513, lon: -85.0849 },
      { icao: 'KTYS', name: 'Knoxville', lat: 35.8118, lon: -83.9940 },
    ],
    distanceNm: 188,
    aircraftCategory: 'SE',
    tags: ['cross-country', 'training', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Nashville_Skyline_from_LP_Field_crop.jpg/1280px-Nashville_Skyline_from_LP_Field_crop.jpg',
    imageCredit: 'Wikipedia / Kaldari',
  },

  // ── NEW YORK ─────────────────────────────────────────────────────────────────
  {
    id: 'ny-hudson-valley',
    stateCode: 'NY',
    region: 'Northeast',
    name: 'Hudson Valley Foliage Run',
    description: 'Follow the legendary Hudson River north from Westchester to Albany. Catskill ridges on the west, the Berkshires to the east — spectacular any time of year, transcendent in October.',
    waypoints: [
      { icao: 'KHPN', name: 'White Plains', lat: 41.0670, lon: -73.7076 },
      { icao: 'KPOU', name: 'Poughkeepsie', lat: 41.6266, lon: -73.8843 },
      { icao: 'KALB', name: 'Albany', lat: 42.7483, lon: -73.8017 },
      { icao: 'KSCH', name: 'Schenectady', lat: 42.8523, lon: -73.9289 },
    ],
    distanceNm: 105,
    aircraftCategory: 'SE',
    tags: ['scenic', 'cross-country', 'historical'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Hudson_Valley_foliage_2.jpg/1280px-Hudson_Valley_foliage_2.jpg',
    imageCredit: 'Wikipedia / Harley Davis',
  },
  {
    id: 'ny-long-island',
    stateCode: 'NY',
    region: 'Northeast',
    name: 'Long Island East End',
    description: 'Fly the Hamptons and Montauk from Farmingdale — one of the best VFR routes in the Northeast. Barrier beaches, exclusive estates, and the open Atlantic stretching east.',
    waypoints: [
      { icao: 'KFRG', name: 'Farmingdale', lat: 40.7288, lon: -73.4134 },
      { icao: 'KFOK', name: 'Westhampton', lat: 40.8437, lon: -72.5179 },
      { icao: 'KMTP', name: 'Montauk', lat: 41.0765, lon: -71.9208 },
    ],
    distanceNm: 72,
    aircraftCategory: 'SE',
    tags: ['coastal', 'scenic', 'urban'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Montauk_Lighthouse_from_the_Air.jpg/1280px-Montauk_Lighthouse_from_the_Air.jpg',
    imageCredit: 'Wikipedia / Eric Salard',
  },
  {
    id: 'ny-finger-lakes',
    stateCode: 'NY',
    region: 'Northeast',
    name: 'Finger Lakes Wine Trail',
    description: 'Fly between New York\'s glacier-carved Finger Lakes — the thin blue fingers of Seneca and Cayuga visible from 4,000 ft, flanked by vineyards and gorges.',
    waypoints: [
      { icao: 'KROC', name: 'Rochester', lat: 43.1189, lon: -77.6724 },
      { icao: 'KITH', name: 'Ithaca', lat: 42.4910, lon: -76.4584 },
      { icao: 'KBGM', name: 'Binghamton', lat: 42.2087, lon: -75.9798 },
    ],
    distanceNm: 118,
    aircraftCategory: 'SE',
    tags: ['scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Seneca_Lake_from_Watkins_Glen.jpg/1280px-Seneca_Lake_from_Watkins_Glen.jpg',
    imageCredit: 'Wikipedia / Bud Ellison',
  },

  // ── MONTANA ─────────────────────────────────────────────────────────────────
  {
    id: 'mt-glacier-country',
    stateCode: 'MT',
    region: 'West',
    name: 'Glacier Country Traverse',
    description: 'Fly through the northern Rockies from Great Falls to Glacier Park International. The Lewis Range rises ahead; on a clear day the peaks of Glacier National Park fill the windscreen.',
    waypoints: [
      { icao: 'KGTF', name: 'Great Falls', lat: 47.4820, lon: -111.3709 },
      { icao: 'KGPI', name: 'Glacier Park', lat: 48.3105, lon: -114.2557 },
      { icao: 'KHVR', name: 'Havre', lat: 48.5430, lon: -109.7623 },
    ],
    distanceNm: 175,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/GNP_-_Logan_Pass_tarn.jpg/1280px-GNP_-_Logan_Pass_tarn.jpg',
    imageCredit: 'Wikipedia / Wing-Chi Poon',
  },
  {
    id: 'mt-big-sky',
    stateCode: 'MT',
    region: 'West',
    name: 'Big Sky Country Loop',
    description: 'Fly the wide-open Montana range country connecting the state capital Helena to Bozeman and Dillon — classic "Big Sky" flying with endless vistas and minimal traffic.',
    waypoints: [
      { icao: 'KBZN', name: 'Bozeman', lat: 45.7777, lon: -111.1529 },
      { icao: 'KHLN', name: 'Helena', lat: 46.6068, lon: -111.9829 },
      { icao: 'KDLN', name: 'Dillon', lat: 45.2553, lon: -112.5533 },
    ],
    distanceNm: 138,
    aircraftCategory: 'SE',
    tags: ['scenic', 'cross-country', 'mountain'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Big_Sky_Country_Montana.jpg/1280px-Big_Sky_Country_Montana.jpg',
    imageCredit: 'Wikipedia / Cre8tor',
  },

  // ── UTAH ────────────────────────────────────────────────────────────────────
  {
    id: 'ut-national-parks',
    stateCode: 'UT',
    region: 'West',
    name: 'National Parks Circuit',
    description: 'Utah has more stunning desert scenery per mile than anywhere in the US. This route connects Provo to Cedar City, St. George, and Milford — overflying Capitol Reef, Bryce, and Zion en route.',
    waypoints: [
      { icao: 'KPVU', name: 'Provo', lat: 40.2192, lon: -111.7234 },
      { icao: 'KCDC', name: 'Cedar City', lat: 37.7010, lon: -113.0988 },
      { icao: 'KSGU', name: 'St. George', lat: 37.0363, lon: -113.5103 },
    ],
    distanceNm: 195,
    aircraftCategory: 'SE',
    tags: ['desert', 'mountain', 'scenic', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Delicatearch_whitesky.jpg/1280px-Delicatearch_whitesky.jpg',
    imageCredit: 'Wikipedia / Jon Sullivan',
  },
  {
    id: 'ut-salt-lake-valley',
    stateCode: 'UT',
    region: 'West',
    name: 'Salt Lake Valley Tour',
    description: 'Fly the Wasatch Front from Salt Lake to Ogden and back — the Great Salt Lake shimmers to the west, ski resorts line the peaks to the east, and the urban valley spreads below.',
    waypoints: [
      { icao: 'KSLC', name: 'Salt Lake City', lat: 40.7884, lon: -111.9778 },
      { icao: 'KOGD', name: 'Ogden-Hinckley', lat: 41.1959, lon: -112.0120 },
      { icao: 'KPVU', name: 'Provo', lat: 40.2192, lon: -111.7234 },
    ],
    distanceNm: 62,
    aircraftCategory: 'SE',
    tags: ['mountain', 'urban', 'training'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Great_Salt_Lake_from_above.jpg/1280px-Great_Salt_Lake_from_above.jpg',
    imageCredit: 'Wikipedia / NASA',
  },

  // ── OREGON ──────────────────────────────────────────────────────────────────
  {
    id: 'or-crater-lake',
    stateCode: 'OR',
    region: 'West',
    name: 'Crater Lake Overfly',
    description: 'Fly over the deepest lake in North America — the brilliant blue caldera of Crater Lake sits at 6,173 ft elevation inside a collapsed volcano. Approach from Redmond and exit to the coast.',
    waypoints: [
      { icao: 'KRDM', name: 'Redmond', lat: 44.2541, lon: -121.1496 },
      { icao: 'KBOK', name: 'Brookings', lat: 42.0746, lon: -124.2901 },
      { icao: 'KOTH', name: 'North Bend/Coos Bay', lat: 43.4171, lon: -124.2458 },
    ],
    distanceNm: 165,
    aircraftCategory: 'SE',
    tags: ['mountain', 'scenic', 'coastal', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Crater_lake_oregon.jpg/1280px-Crater_lake_oregon.jpg',
    imageCredit: 'Wikipedia / Zainubrazvi',
  },
  {
    id: 'or-columbia-gorge',
    stateCode: 'OR',
    region: 'West',
    name: 'Columbia River Gorge',
    description: 'Follow the Columbia River east from Portland through the spectacular basalt gorge. Waterfalls tumble from both walls, and Mt. Hood presides over the Cascades to the south.',
    waypoints: [
      { icao: 'KHIO', name: 'Hillsboro', lat: 45.5404, lon: -122.9498 },
      { icao: 'KDLS', name: 'The Dalles', lat: 45.6185, lon: -121.1664 },
      { icao: 'KPDT', name: 'Pendleton', lat: 45.6950, lon: -118.8415 },
    ],
    distanceNm: 138,
    aircraftCategory: 'SE',
    tags: ['scenic', 'mountain', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Columbia_River_Gorge_from_Crown_Point.jpg/1280px-Columbia_River_Gorge_from_Crown_Point.jpg',
    imageCredit: 'Wikipedia / Cacophony',
  },

  // ── NEW MEXICO ───────────────────────────────────────────────────────────────
  {
    id: 'nm-enchanted-skies',
    stateCode: 'NM',
    region: 'West',
    name: 'Land of Enchantment Skyway',
    description: 'New Mexico\'s high desert landscape is unmatched — fly from Albuquerque along the Rio Grande to Santa Fe and Taos. Adobe pueblos, sage plains, and the Sangre de Cristos frame the route.',
    waypoints: [
      { icao: 'KABQ', name: 'Albuquerque', lat: 35.0402, lon: -106.6090 },
      { icao: 'KSAF', name: 'Santa Fe', lat: 35.6171, lon: -106.0883 },
      { icao: 'KTAO', name: 'Taos', lat: 36.4582, lon: -105.6719 },
    ],
    distanceNm: 95,
    aircraftCategory: 'SE',
    tags: ['desert', 'mountain', 'historical', 'scenic'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Sandia_Peak_Aerial_Tram.jpg/1280px-Sandia_Peak_Aerial_Tram.jpg',
    imageCredit: 'Wikipedia / Billy Hathorn',
  },
  {
    id: 'nm-white-sands',
    stateCode: 'NM',
    region: 'West',
    name: 'White Sands & Roswell',
    description: 'Cross the Tularosa Basin to the blindingly white gypsum dunes of White Sands, then north to Roswell — landing at the "UFO Capital of the World."',
    waypoints: [
      { icao: 'KROW', name: 'Roswell', lat: 33.3016, lon: -104.5306 },
      { icao: 'KHOB', name: 'Hobbs', lat: 32.6875, lon: -103.2172 },
      { icao: 'KALM', name: 'Alamogordo-White Sands', lat: 32.8400, lon: -105.9906 },
    ],
    distanceNm: 130,
    aircraftCategory: 'SE',
    tags: ['desert', 'historical', 'cross-country'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/White_Sands_New_Mexico.jpg/1280px-White_Sands_New_Mexico.jpg',
    imageCredit: 'Wikipedia / Michael Barera',
  },
]

export function getRoutesByState(stateCode: string): CuratedRoute[] {
  return curatedRoutes.filter(r => r.stateCode === stateCode)
}

export function getRouteById(id: string): CuratedRoute | undefined {
  return curatedRoutes.find(r => r.id === id)
}

export function getFeaturedRoutes(count = 6): CuratedRoute[] {
  const featured = [
    'ca-bay-tour', 'hi-inter-island', 'ak-kenai-peninsula',
    'az-grand-canyon', 'co-mountain-passes', 'fl-florida-keys',
    'wa-san-juan-islands', 'ny-hudson-valley', 'or-crater-lake',
  ]
  return featured
    .map(id => curatedRoutes.find(r => r.id === id))
    .filter(Boolean)
    .slice(0, count) as CuratedRoute[]
}

export const statesWithRoutes = [...new Set(curatedRoutes.map(r => r.stateCode))]
